### ISSUE TITLE
Error XML-Parser

### ISSUE THREAD

**Issue by karsc96** [nkl-kst/MMM-RBB-Weather#58]
Hey There,
having some issues with multiple error messages. The module shows "no data".
Here the error messages from console:

> TypeError: xmlParser.parse is not a function
>     at Class.parseData (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:137:38)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:112:39)
>     at IncomingMessage.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> [02.02.2024 20:55.32.392] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [02.02.2024 20:55.32.393] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> [02.02.2024 20:55.32.409] [ERROR] Whoops! There was an uncaught exception...
> [02.02.2024 20:55.32.414] [ERROR] TypeError: xmlParser.parse is not a function
>     at Class.parseData (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:137:38)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:112:39)
>     at IncomingMessage.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> [02.02.2024 20:55.32.417] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [02.02.2024 20:55.32.418] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> [02.02.2024 20:55.32.425] [ERROR] Whoops! There was an uncaught exception...
> [02.02.2024 20:55.32.427] [ERROR] TypeError: xmlParser.parse is not a function
>     at Class.parseData (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:137:38)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:112:39)
>     at IncomingMessage.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> [02.02.2024 20:55.32.430] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [02.02.2024 20:55.32.433] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> [02.02.2024 20:55.32.451] [ERROR] Whoops! There was an uncaught exception...
> [02.02.2024 20:55.32.453] [ERROR] TypeError: xmlParser.parse is not a function
>     at Class.parseData (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:137:38)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:112:39)
>     at IncomingMessage.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> [02.02.2024 20:55.32.454] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [02.02.2024 20:55.32.455] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> [02.02.2024 20:55.32.465] [ERROR] Whoops! There was an uncaught exception...
> [02.02.2024 20:55.32.469] [ERROR] TypeError: xmlParser.parse is not a function
>     at Class.parseData (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:137:38)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-RBB-Weather/node_helper.js:112:39)
>     at IncomingMessage.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 

Also expiriencing another issue with stylesheet (error from dev mode electron browser). Not sure if this relates to the XML parser problems from above. Will therefore open a separate ticket.

Raspbian 10 (buster)
Running MM 2.26.0
nodejs V18

What other information are needed?
Thanks in advance.
Best regards

**Comment by karsc96** [comment]
Will close this issue now after it started working again.
I reseted (git reset --hard) set nvm explicitly to 18 (nvm use 18) and reinstalled the module. For some reason there were two npm versions installed (18 and 20).
Now it works again.
Thanks anyway for trying to help a bit.
